package com.cqust.dao;

import com.cqust.model.merchbill;
import com.cqust.model.merchbillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface merchbillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    long countByExample(merchbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int deleteByExample(merchbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int deleteByPrimaryKey(String merchid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int insert(merchbill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int insertSelective(merchbill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    List<merchbill> selectByExampleWithBLOBs(merchbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    List<merchbill> selectByExample(@Param(value = "page") Integer page,@Param(value = "limit") Integer limit);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    merchbill selectByPrimaryKey(String merchid);
    /*根据类别查询*/
    List<merchbill> selectBykind(@Param("kind") String merchid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int updateByExampleSelective(@Param("record") merchbill record, @Param("example") merchbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") merchbill record, @Param("example") merchbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int updateByExample(@Param("record") merchbill record, @Param("example") merchbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int updateByPrimaryKeySelective(merchbill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(merchbill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int updateByPrimaryKey(merchbill record);
}