package com.cqust.dao;

import com.cqust.model.profferbill;
import com.cqust.model.profferbillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface profferbillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profferbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    long countByExample();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profferbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int deleteByExample(profferbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profferbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int deleteByPrimaryKey(String profferid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profferbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int insert(profferbill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profferbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int insertSelective(profferbill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profferbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    List<profferbill> selectByExampleWithBLOBs(profferbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profferbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    List<profferbill> selectByExample(@Param(value = "page") Integer page,@Param(value = "limit") Integer limit);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profferbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    profferbill selectByPrimaryKey(String profferid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profferbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int updateByExampleSelective(@Param("record") profferbill record, @Param("example") profferbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profferbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") profferbill record, @Param("example") profferbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profferbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int updateByExample(@Param("record") profferbill record, @Param("example") profferbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profferbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int updateByPrimaryKeySelective(profferbill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profferbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(profferbill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profferbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int updateByPrimaryKey(profferbill record);
    /*按条件查询*/
    List<profferbill> selectCondition(@Param("record")profferbill profferbill);
}