package com.cqust.dao;

import com.cqust.model.salebill;
import com.cqust.model.salebillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface salebillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salebill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    long countByExample(salebillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salebill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int deleteByExample(salebillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salebill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int deleteByPrimaryKey(String salebillid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salebill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int insert(salebill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salebill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int insertSelective(salebill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salebill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    List<salebill> selectByExample(@Param(value = "page") Integer page,@Param(value = "limit") Integer limit);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salebill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    salebill selectByPrimaryKey(String  salebillid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salebill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int updateByExampleSelective(@Param("record") salebill record, @Param("example") salebillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salebill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int updateByExample(@Param("record") salebill record, @Param("example") salebillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salebill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int updateByPrimaryKeySelective(salebill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salebill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int updateByPrimaryKey(salebill record);
}