package com.cqust.dao;

import com.cqust.model.staffbill;
import com.cqust.model.staffbillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface staffbillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staffbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    long countByExample();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staffbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int deleteByExample(staffbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staffbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int deleteByPrimaryKey(String staffid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staffbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int insert(staffbill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staffbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int insertSelective(staffbill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staffbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    List<staffbill> selectByExampleWithBLOBs();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staffbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    List<staffbill> selectByExample(@Param(value = "page") Integer page,@Param(value = "limit") Integer limit);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staffbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    staffbill selectByPrimaryKey(String staffid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staffbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int updateByExampleSelective(@Param("record") staffbill record, @Param("example") staffbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staffbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") staffbill record, @Param("example") staffbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staffbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int updateByExample(@Param("record") staffbill record, @Param("example") staffbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staffbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int updateByPrimaryKeySelective(staffbill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staffbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(staffbill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staffbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int updateByPrimaryKey(staffbill record);
}