package com.cqust.dao;

import com.cqust.model.storebill;
import com.cqust.model.storebillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface storebillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storebill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    long countByExample(storebillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storebill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int deleteByExample(storebillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storebill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int deleteByPrimaryKey(String merchid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storebill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int insert(storebill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storebill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int insertSelective(storebill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storebill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    List<storebill> selectByExample(@Param(value = "page") Integer page,@Param(value = "limit") Integer limit);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storebill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    storebill selectByPrimaryKey(String merchid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storebill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int updateByExampleSelective(@Param("record") storebill record, @Param("example") storebillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storebill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int updateByExample(@Param("record") storebill record, @Param("example") storebillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storebill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int updateByPrimaryKeySelective(storebill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storebill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int updateByPrimaryKey(storebill record);
}