package com.cqust.model;

public class importbillKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importbill.imortBillID
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private String imortbillid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importbill.merchID
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private String merchid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importbill.imortBillID
     *
     * @return the value of importbill.imortBillID
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public String getImortbillid() {
        return imortbillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importbill.imortBillID
     *
     * @param imortbillid the value for importbill.imortBillID
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setImortbillid(String imortbillid) {
        this.imortbillid = imortbillid == null ? null : imortbillid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importbill.merchID
     *
     * @return the value of importbill.merchID
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public String getMerchid() {
        return merchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importbill.merchID
     *
     * @param merchid the value for importbill.merchID
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setMerchid(String merchid) {
        this.merchid = merchid == null ? null : merchid.trim();
    }
}