package com.cqust.model;

import java.util.Date;

public class importbill extends importbillKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importbill.profferID
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private String profferid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importbill.importPrice
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private Double importprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importbill.quantity
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importbill.totalMoney
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private Double totalmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importbill.importDate
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private Date importdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importbill.other
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private String other;
    
    private merchbill merchbill;
    
    private profferbill profferbill;
    
    
    

    public profferbill getProfferbill() {
		return profferbill;
	}

	public void setProfferbill(profferbill profferbill) {
		this.profferbill = profferbill;
	}

	public merchbill getMerchbill() {
		return merchbill;
	}

	public void setMerchbill(merchbill merchbill) {
		this.merchbill = merchbill;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importbill.profferID
     *
     * @return the value of importbill.profferID
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public String getProfferid() {
        return profferid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importbill.profferID
     *
     * @param profferid the value for importbill.profferID
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setProfferid(String profferid) {
        this.profferid = profferid == null ? null : profferid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importbill.importPrice
     *
     * @return the value of importbill.importPrice
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public Double getImportprice() {
        return importprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importbill.importPrice
     *
     * @param importprice the value for importbill.importPrice
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setImportprice(Double importprice) {
        this.importprice = importprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importbill.quantity
     *
     * @return the value of importbill.quantity
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importbill.quantity
     *
     * @param quantity the value for importbill.quantity
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importbill.totalMoney
     *
     * @return the value of importbill.totalMoney
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public Double getTotalmoney() {
        return totalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importbill.totalMoney
     *
     * @param totalmoney the value for importbill.totalMoney
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setTotalmoney(Double totalmoney) {
        this.totalmoney = totalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importbill.importDate
     *
     * @return the value of importbill.importDate
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public Date getImportdate() {
        return importdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importbill.importDate
     *
     * @param importdate the value for importbill.importDate
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setImportdate(Date importdate) {
        this.importdate = importdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importbill.other
     *
     * @return the value of importbill.other
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importbill.other
     *
     * @param other the value for importbill.other
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }
}