package com.cqust.model;

public class merchbill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchbill.merchID
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private String merchid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchbill.profferID
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private String profferid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchbill.fullName
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private String fullname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchbill.kind
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private String kind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchbill.birthPlace
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private String birthplace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchbill.unitCost
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private Double unitcost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchbill.other
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private String other;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchbill.merchID
     *
     * @return the value of merchbill.merchID
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public String getMerchid() {
        return merchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchbill.merchID
     *
     * @param merchid the value for merchbill.merchID
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setMerchid(String merchid) {
        this.merchid = merchid == null ? null : merchid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchbill.profferID
     *
     * @return the value of merchbill.profferID
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public String getProfferid() {
        return profferid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchbill.profferID
     *
     * @param profferid the value for merchbill.profferID
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setProfferid(String profferid) {
        this.profferid = profferid == null ? null : profferid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchbill.fullName
     *
     * @return the value of merchbill.fullName
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchbill.fullName
     *
     * @param fullname the value for merchbill.fullName
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setFullname(String fullname) {
        this.fullname = fullname == null ? null : fullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchbill.kind
     *
     * @return the value of merchbill.kind
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public String getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchbill.kind
     *
     * @param kind the value for merchbill.kind
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setKind(String kind) {
        this.kind = kind == null ? null : kind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchbill.birthPlace
     *
     * @return the value of merchbill.birthPlace
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public String getBirthplace() {
        return birthplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchbill.birthPlace
     *
     * @param birthplace the value for merchbill.birthPlace
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setBirthplace(String birthplace) {
        this.birthplace = birthplace == null ? null : birthplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchbill.unitCost
     *
     * @return the value of merchbill.unitCost
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public Double getUnitcost() {
        return unitcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchbill.unitCost
     *
     * @param unitcost the value for merchbill.unitCost
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setUnitcost(Double unitcost) {
        this.unitcost = unitcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchbill.other
     *
     * @return the value of merchbill.other
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchbill.other
     *
     * @param other the value for merchbill.other
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }
}