package com.cqust.model;

public class profferbill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profferbill.profferID
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private String profferid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profferbill.fullName
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private String fullname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profferbill.contactPerson
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private String contactperson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profferbill.phone
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profferbill.address
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profferbill.openingBank
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private String openingbank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profferbill.accountID
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private String accountid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profferbill.other
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private String other;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profferbill.profferID
     *
     * @return the value of profferbill.profferID
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public String getProfferid() {
        return profferid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profferbill.profferID
     *
     * @param profferid the value for profferbill.profferID
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setProfferid(String profferid) {
        this.profferid = profferid == null ? null : profferid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profferbill.fullName
     *
     * @return the value of profferbill.fullName
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profferbill.fullName
     *
     * @param fullname the value for profferbill.fullName
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setFullname(String fullname) {
        this.fullname = fullname == null ? null : fullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profferbill.contactPerson
     *
     * @return the value of profferbill.contactPerson
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public String getContactperson() {
        return contactperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profferbill.contactPerson
     *
     * @param contactperson the value for profferbill.contactPerson
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setContactperson(String contactperson) {
        this.contactperson = contactperson == null ? null : contactperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profferbill.phone
     *
     * @return the value of profferbill.phone
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profferbill.phone
     *
     * @param phone the value for profferbill.phone
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profferbill.address
     *
     * @return the value of profferbill.address
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profferbill.address
     *
     * @param address the value for profferbill.address
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profferbill.openingBank
     *
     * @return the value of profferbill.openingBank
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public String getOpeningbank() {
        return openingbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profferbill.openingBank
     *
     * @param openingbank the value for profferbill.openingBank
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setOpeningbank(String openingbank) {
        this.openingbank = openingbank == null ? null : openingbank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profferbill.accountID
     *
     * @return the value of profferbill.accountID
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public String getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profferbill.accountID
     *
     * @param accountid the value for profferbill.accountID
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setAccountid(String accountid) {
        this.accountid = accountid == null ? null : accountid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profferbill.other
     *
     * @return the value of profferbill.other
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profferbill.other
     *
     * @param other the value for profferbill.other
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }
}