package com.cqust.model;

import java.util.Date;

public class staffbill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staffbill.staffID
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private String staffid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staffbill.name
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staffbill.sex
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staffbill.diploma
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private String diploma;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staffbill.salary
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private Integer salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staffbill.phone
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staffbill.address
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staffbill.idCard
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private String idcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staffbill.beginDate
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private Date begindate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staffbill.other
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private String other;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staffbill.staffID
     *
     * @return the value of staffbill.staffID
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public String getStaffid() {
        return staffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staffbill.staffID
     *
     * @param staffid the value for staffbill.staffID
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setStaffid(String staffid) {
        this.staffid = staffid == null ? null : staffid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staffbill.name
     *
     * @return the value of staffbill.name
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staffbill.name
     *
     * @param name the value for staffbill.name
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staffbill.sex
     *
     * @return the value of staffbill.sex
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staffbill.sex
     *
     * @param sex the value for staffbill.sex
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staffbill.diploma
     *
     * @return the value of staffbill.diploma
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public String getDiploma() {
        return diploma;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staffbill.diploma
     *
     * @param diploma the value for staffbill.diploma
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setDiploma(String diploma) {
        this.diploma = diploma == null ? null : diploma.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staffbill.salary
     *
     * @return the value of staffbill.salary
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public Integer getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staffbill.salary
     *
     * @param salary the value for staffbill.salary
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setSalary(Integer salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staffbill.phone
     *
     * @return the value of staffbill.phone
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staffbill.phone
     *
     * @param phone the value for staffbill.phone
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staffbill.address
     *
     * @return the value of staffbill.address
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staffbill.address
     *
     * @param address the value for staffbill.address
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staffbill.idCard
     *
     * @return the value of staffbill.idCard
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staffbill.idCard
     *
     * @param idcard the value for staffbill.idCard
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staffbill.beginDate
     *
     * @return the value of staffbill.beginDate
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public Date getBegindate() {
        return begindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staffbill.beginDate
     *
     * @param begindate the value for staffbill.beginDate
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setBegindate(Date begindate) {
        this.begindate = begindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staffbill.other
     *
     * @return the value of staffbill.other
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staffbill.other
     *
     * @param other the value for staffbill.other
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }
}