package com.cqust.model;

public class storebill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storebill.merchID
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private String merchid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storebill.storeNum
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private Integer storenum;
    
    private merchbill merchbill;
    

    public merchbill getMerchbill() {
		return merchbill;
	}

	public void setMerchbill(merchbill merchbill) {
		this.merchbill = merchbill;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storebill.merchID
     *
     * @return the value of storebill.merchID
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public String getMerchid() {
        return merchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storebill.merchID
     *
     * @param merchid the value for storebill.merchID
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setMerchid(String merchid) {
        this.merchid = merchid == null ? null : merchid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storebill.storeNum
     *
     * @return the value of storebill.storeNum
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public Integer getStorenum() {
        return storenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storebill.storeNum
     *
     * @param storenum the value for storebill.storeNum
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setStorenum(Integer storenum) {
        this.storenum = storenum;
    }
}