package com.cqust.model;

public class userbill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbill.loginID
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private String loginid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbill.passWord
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbill.loginID
     *
     * @return the value of userbill.loginID
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public String getLoginid() {
        return loginid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbill.loginID
     *
     * @param loginid the value for userbill.loginID
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setLoginid(String loginid) {
        this.loginid = loginid == null ? null : loginid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbill.passWord
     *
     * @return the value of userbill.passWord
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbill.passWord
     *
     * @param password the value for userbill.passWord
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}